### ISSUE TITLE
Displaying multiple SkeletonPlaceholder components at the same time severely drops framerate

### ISSUE THREAD

**Issue by jfbn** [chramos/react-native-skeleton-placeholder#31] opened 2021-03-25 11:03 UTC
I have a bunch of components that each render SkeletonPlaceholders until they receive the data they need to become actually useful.

Whenever my app is displaying multiple different SkeletonPlaceholders it becomes extremely laggy. Am I using the library wrongly or what's happening?

**Comment by chramos** [comment] 2021-03-29 10:39
Hey @jfbn, What platform are you facing lag? Android... IOS or both?

**Comment by jfbn** [comment] 2021-03-29 10:44
The lag is more severe on Android, but I do experience it on IOS as well.

**Comment by chramos** [comment] 2021-03-29 11:42
on Android we have a bad performance but its related to `react-native-masked-view` I tried to solve but no success yet.
Try to run your project in release mode to see if the lag exists, I think will running much better. Debug mode is very slow and heavy

**Comment by jfbn** [comment] 2021-04-06 07:50
> on Android we have a bad performance but its related to `react-native-masked-view` I tried to solve but no success yet.
> Try to run your project in release mode to see if the lag exists, I think will running much better. Debug mode is very slow and heavy

Even in release mode the performance is sadly too poor for me to use the library. I think I should just learn to use the library in a way where I am not rendering 6-10 SkeletonPlaceholders at the same time.

**Comment by erick-hdz-sinergis** [comment] 2021-04-07 21:21
I've the same problem, and I'm only showing 3 skeleton's in a view :(

**Comment by oguzturker8** [comment] 2021-04-11 14:30
same, just showing 2 skeleton

**Comment by andreialecu** [comment] 2021-04-15 07:10
I believe this is the same issue as #23 which was supposed to be fixed by: https://github.com/react-native-masked-view/masked-view/pull/98

However, the problem is that this package uses the old library from `@react-native-community`. It has been moved to: `@react-native-masked-view/masked-view`

The dependencies would need to be updated to point to the correct libs: https://github.com/chramos/react-native-skeleton-placeholder/blob/bdf1d204c237fee5f5e823c63fe2be87b1139520/package.json#L30

I haven't yet verified that it fixes the problem. But the steps above would be a good thing to do regardless.

**Comment by mhmdiqbal** [comment] 2021-04-20 16:39
same problem so laggy

**Comment by andreialecu** [comment] 2021-04-21 09:12
#37 should fix this

**Closed** 2021-04-26 14:33 UTC
