### ISSUE TITLE
Outdated masked view package

### ISSUE THREAD

**Issue by jarvisluong** [chramos/react-native-skeleton-placeholder#70] opened 2021-11-04 14:37 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-skeleton-placeholder@5.0.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js b/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js
index 3c35038..41f7a8f 100644
--- a/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js
+++ b/node_modules/react-native-skeleton-placeholder/lib/SkeletonPlaceholder.js
@@ -35,7 +35,7 @@ var __importDefault = (this && this.__importDefault) || function (mod) {
 Object.defineProperty(exports, "__esModule", { value: true });
 const React = __importStar(require("react"));
 const react_native_1 = require("react-native");
-const masked_view_1 = __importDefault(require("@react-native-masked-view/masked-view"));
+const masked_view_1 = __importDefault(require("@react-native-community/masked-view"));
 const react_native_linear_gradient_1 = __importDefault(require("react-native-linear-gradient"));
 const SCREEN_WIDTH = react_native_1.Dimensions.get("window").width;
 function SkeletonPlaceholder({ children, backgroundColor = "#E1E9EE", speed = 800, highlightColor = "#F2F8FC", direction = "right", }) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by DnEgorWeb** [comment] 2021-11-12 17:32
For anyone who is considering solution above:

If the issue is react-navigation using @react-native-community/masked-view - such patch is not relevant for react-navigation v6 (it does not have masked-view dependency). To avoid incompatibility either use @react-native-community/masked-view v4 or upgrade your react-navigation to v6.

**Comment by chramos** [comment] 2022-10-17 19:16
fixed in the latest release

**Closed by chramos** 2022-10-17 19:16 UTC
